version: 2
jobs:
  build:
    environment: #match these to your .env file!
      PGRST_DB_URI: postgres://ubuntu@localhost:5432/circle_test
      POSTGRES_DB: circle_test
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ""
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      PGRST_DB_ANON_ROLE: ubuntu
      PGRST_DB_SCHEMA: public
      
    working_directory: ~/circleci-2.0-pytest-postgresql
    
    docker:
      # main python worker image
      - image: circleci/python:3.7.3
          
      # database dev instance
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
          
      # postgrest database connector
      - image: postgrest/postgrest
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Setup the database
          command: psql -h $DATABASE_HOSTNAME -p $DATABASE_PORT -U $POSTGRES_USER -d $POSTGRES_DB -a -f schema.sql
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test tests --junitxml=test-reports/output.xml
            
