version: 2
jobs:
  build:
    environment: #match these to your .env file!
      DATABASE_URL: postgres://ubuntu@localhost:5432/circle_test
      DATABASE_NAME: circle_test
      DATABASE_USER: ubuntu
      DATABASE_PASSWORD: ""
      DATABASE_SCHEMA: public
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      
    working_directory: ~/circleci-2.0-pytest-postgresql
    
    docker:
      # main python worker image
      - image: circleci/python:3.7.3
          
      # database dev instance
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
          
      # postgrest database connector
      - image: postgrest/postgrest
        environment:
          PGRST_DB_URI: $DATABASE_URL
          PGRST_DB_SCHEMA: $DATABASE_SCHEMA
          PGRST_DB_ANON_ROLE: $DATABASE_USER #In production this role should not be the same as the one used for the connection
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Setup the database
          command: psql -h $DATABASE_HOSTNAME -p $DATABASE_PORT -U $DATABASE_USER -d $DATABASE_NAME -a -f schema.sql
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test tests --junitxml=test-reports/output.xml
            
