version: 2
jobs:
  build:
    working_directory: ~/circleci-2.0-pytest-postgresql
    docker:
    
      # main python worker image
      - image: circleci/python:3.7.3
        environment:
          DATABASE_URL: postgres://ubuntu@localhost:5432/circle_test
          DB_NAME: circle_test
          
      # database dev instance
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
          
      # postgrest database connector
      - image: postgrest/postgrest
        environment:
          PGRST_DB_URI: postgres://ubuntu@localhost:5432/circle_test
          PGRST_DB_SCHEMA: public
          PGRST_DB_ANON_ROLE: ubuntu #In production this role should not be the same as the one used for the connection
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Setup the database
          command: psql -h localhost -p 5432 -U ubuntu -d circle_test -a -f schema.sql
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test tests --junitxml=test-reports/output.xml
